version: '3.8'

services:
  rd2tb:
    image: arrrrrr/rd2tb:27
    container_name: rd2tb
    volumes:
      - /yourzurgvolume/zurgdata:/zurgdata
      - ./:/app/data
    environment:
      - TORBOX_API_TOKEN=#yourapi
      - ZURGDATA_FOLDER=/zurgdata
      - TORBOX_MAX_CONCURRENT=3
    restart: unless-stopped
